# MySQL.  Versions 5.0+ are recommended.
#
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  host: localhost
  charset: utf8
  collation: utf8_unicode_ci

local:
  <<: *default
  database: mackun2_local
  password: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mackun2_development
  username: root
  password: root
  host: localhost

test:
  <<: *default
  # Temporal
  encoding: utf8
  charset: utf8
  collation: utf8_unicode_ci
  password: root
  database: mackun2_test
  socket: /tmp/mysql.sock

production:
  <<: *default
  host:
  database: mackun2_production
  username: mackun2
  password: <%= ENV['MACKUN2_DATABASE_PASSWORD'] %>
